### ISSUE TITLE
interaction with public repo URL

### ISSUE THREAD

**Issue by grantmacken** [eXist-db/public-xar-repo#26]
I am building a simple CLI package manager that interacts with the public repo to 
list, update, get, remove and search for eXist packages.

Going  from the repo doc provided at
http://localhost:8080/exist/apps/doc/repo
a request of
http://demo.exist-db.org/exist/apps/public-repo/public/apps.xml
provides a list of available apps.

What I have found is the 'version'   '/apps/app/version/string()' 
is not the latest 'version', which is found by moving further down the XML tree

example:  curl  http://demo.exist-db.org/exist/apps/public-repo/public/apps.xml
```
<app path="shared-resources-0.4.2.xar" size="2121495">
<version>0.4.2</version>
<name>http://exist-db.org/apps/shared</name>
...
<other>
  <version version="0.6.0" path="shared-resources-0.6.0.xar">
```
 the latest version is "0.6.0'  via  '/apps/app/other/version/@version'
      this differs from   '0.4.2'  via '/apps/app/version/string()'

I have created a work around but surely ' /apps/app/version' should signify the latest version

**Comment by joewiz** [comment]
The phenomenon you observe is caused by the public repo's default behavior: to display apps compatible with eXist 2.2.0, unless a version parameter is supplied. For the `apps.xml` endpoint, you can supply a `version` parameter, e.g., http://demo.exist-db.org/exist/apps/public-repo/public/apps.xml?version=4.2.1 would return apps whose minimum required version is 4.2.1 or lower. For the `packages` endpoint, which is linked from http://demo.exist-db.org/exist/apps/public-repo/index.html, you can supply a `eXist-db-min-version` parameter, e.g., http://demo.exist-db.org/exist/apps/public-repo/packages/shared.html?eXist-db-min-version=4.2.1.

Do these parameters provide what you are looking for?

**Comment by grantmacken** [comment]
Thanks Joe.
That's what I was missing.
After playing around I realized the atom feed, showed the latest versions,
so I thought there might be some extra endpoint URL args required.

**Comment by adamretter** [comment]
@joewiz So... I think it displays apps compatible with eXist 2.2.0 as there was some problem in version matching in the past? Perhaps we could add add attribute to the output that makes this obvious e.g.

`exist-compatible-version="2.2.0"`

That value will obviously change if you supply a `version` parameter.
